module.exports = function(content) {
  [
    ['alert',      'внимание\s*\(',                  'alert('],
    ['console',    'консоль\.',                      'console.'],
    ['log',        'console\.(логировать|лог)\s*\(', 'console.log('],
    ['break',      'стоп(;|\s+)',                    'break$1'],
    ['case',       'случай\s+',                      'case '],
    ['class',      'класс\s+',                       'class '],
    ['catch',      'поймать\s*\(',                   'catch('],
    ['const',      'константа\s+',                   'const '],
    ['continue',   'продолжить(;|\s+)',              'continue$1'],
    ['default',    'поумолчанию\s*:',                'default:'],
    ['delete',     'удалить\s+',                     'delete '],
    ['do',         'сделай(\s*{|\s+)',               'do$1'],
    ['else',       'иначе(\s+|\{)',                  'else$1'],
    ['export',     'экспортировать\s+',              'export '],
    ['extends',    '\s+расширяет\s+',                ' extends '],
    ['finally',    'вконце(\s+|\{)',                 'finally$1'],
    ['for',        'цикл(\s*\()',                    'for ('],
    ['function',   'функция(\s+|\()',                'function$1'],
    ['if',         'если\s*\(',                      'if ('],
    ['import',     'импортировать\s+',               'import '],
    [' in ',       '\s+в\s+',                        ' in '],
    ['instanceof', '\s+экземпляр(\s+|\()',           ' instanceof$1'],
    ['let',        'пусть\s+',                       'let '],
    ['new',        'новый\s+',                       'new '],
    [' of ',       '\s+из\s+',                       ' of '],
    ['return',     'вернуть\s+',                     'return '],
    ['super',      'супер\s*(',                      'super('],
    ['switch',     'перебрать\s*\(',                 'switch ('],
    ['this',       'тут|этот',                       ' this'],
    ['throw',      'бросить\s+',                     'throw '],
    ['try',        'попробывать(\s+|\s*{)',          'try$1'],
    ['typeof',     'тип(\s+|\s*\()',                 'typeof$1'],
    ['var ',       'пер(еменная)?\s+',               'var '],
    ['void',       'пусто\s*\(',                     'void('],
    ['while',      'пока\s*\(',                      'while ('],
    ['with',       'совместно\s*\(',                 'with ('],
    ['yield',      'уступить\s+',                    'yield '],
    ['pop',        '\.сократить\(\)',                '.pop()'],
    ['push',       '\.добавить\(',                   '.push('],
    ['reverse',    '\.отразить\(\)',                 '.reverse()'],
    ['shift',      '\.сдвинуть\(\)',                 '.shift()'],
    ['sort',       '\.сортировать\(',                '.sort('],
    ['splice',     '\.соединить\(',                  '.splice('],
    ['unshift',    '\.раздвинуть\(',                 '.unshift('],
    ['concat',     '\.связать\(',                    '.concat('],
    ['join',       '\.объединить\(',                 '.join('],
    ['slice',      '\.срез\(',                       '.slice('],
    ['toString',   '\.в(c|С)троку\(\)',              '.toSrtring()'],
    ['indexOf',    '\.номер(В|в)\(',                 '.indexOf('],
    ['forEach',    '\.для(К|к)аждого\(',             '.forEach('],
    ['every',      '\.каждый\(',                     '.every('],
    ['some',       '\.хоть(О|о)дин\(',               '.some('],
    ['filter',     '\.фильтр\(',                     '.filter('],
    ['map',        '\.карта\(',                      '.map('],
    ['reduce',     '\.свести\(',                     '.reduce('],
    ['prototype',  '\.прототип(\.|\s+)',             '.prototype$1'],
    ['length  ',   '\.длинна',                       '.length'],
  ].forEach(function(en) {
    content.replace(new RegExp(en[1], 'g', en[2]));
  });

  return content;
}